replicaCount: 1

image:
  repository: telemetryguardacr17j8.azurecr.io/api
  tag: v8
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

prometheus:
  path: /metrics
  port: 8000

podAnnotations:
  azure.workload.identity/client-id: cbb07ae7-03b2-4a81-8df4-2382f65a3969

env:
  - name: MLFLOW_TRACKING_URI
    value: "http://telemetryguard-mlflow-service.default.svc.cluster.local:5050"

livenessProbe:
  path: /health
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6

resources: {}
