


# Prometheus configuration file
global:
  scrape_interval: 5s #collect metrics every 5 seceonds
  evaluation_interval: 10s # Evaluate alert rules every 10 seconds (if any)

scrape_configs:
    - job_name: "telemetryguard_api" #name of the job
      metrics_path: /metrics #FastAPI metrics endpoint
      static_configs:
        -targets: ["api:8000"]
        -labels:
          service: "telemetryguard_api"
          environment: "local"
          model: "stroke_prediction"

    - job_name: "prometheus"
      static_configs:
      -targets: ["prometheus:9090"]
