apiVersion: v1
kind: Service
metadata:
  name: telemetryguard-mlflow-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: telemetryguard-mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
