replicaCount: 1

image:
  repository: telemetryguardacr17j8.azurecr.io/mlflow
  tag: v0.2.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5050
  targetPort: 5050

podAnnotations:
  azure.workload.identity/client-id: fb6697e5-0a91-4925-b0bd-4d9bea7e8b07

env:
  - name: MLFLOW_ARTIFACT_ROOT
    value: "file:/mlflow-artifacts"
  - name: MLFLOW_BACKEND_STORE_URI
    value: "sqlite:///mlflow.db"
  - name: MLFLOW_TRACKING_URI
    value: "http://0.0.0.0:5050"


artifactStorage:
  accountName: telemetryguardstore17j8


resources: {}
