apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetryguard-mlflow
  labels:
    app: telemetryguard-mlflow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: telemetryguard-mlflow
  template:
    metadata:
      labels:
        app: telemetryguard-mlflow
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: telemetryguard-mlflow-sa
      containers:
        - name: telemetryguard-mlflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["mlflow"]
          args:
            - "server"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "{{ .Values.service.port }}"
            - "--backend-store-uri"
            - "sqlite:///mlflow.db"
            #- "--artifacts-destination"
            #- "http://127.0.0.1:5050/"
            #- "--default-artifact-root"
            #- "file:/mlflow-artifacts"
            - "--serve-artifacts"
            - "--artifacts-destination"
            - "file:/mlflow-artifacts"
          env:
            {{- toYaml .Values.env | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: mlflow-artifacts
              mountPath: /mlflow-artifacts
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: mlflow-artifacts
          emptyDir: {}
      restartPolicy: Always
