apiVersion: v1
kind: Service
metadata:
  name: telemetryguard-mlflow-service
  labels:
    app: telemetryguard-mlflow
spec:
  type: ClusterIP
  selector:
    app: telemetryguard-mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
