apiVersion: v1
kind: Service
metadata:
  name: telemetryguard-mlflow-service
  labels:
    app: telemetryguard-mlflow
spec:
  type: {{ .Values.service.type }}
  selector:
    app: telemetryguard-mlflow
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
