apiVersion: v1
kind: Service
metadata:
  name: telemetryguard-api-service
  labels:
    app: telemetryguard-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: telemetryguard-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
