apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetryguard-api-sa
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "cbb07ae7-03b2-4a81-8df4-2382f65a3969"
